Apartment.App/Apartment.App.Web/Controllers/BlockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using Apartment.App.Business.Abstract;
using Apartment.App.Business.DTO;
using Apartment.App.Domain.Entities;
using Apartment.App.Web.Models.BlockModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace Apartment.App.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlockController : Controller
    {
        private IBlockService blockService;
        private IFloorService floorService;
        private IHousingService housingService;
        private IMapper mapper;
        public BlockController(IBlockService blockService, IFloorService floorService, IHousingService housingService, IMapper mapper)
        {
            this.blockService = blockService;
            this.floorService = floorService;
            this.housingService = housingService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var blocksassd = blockService.GetAll();
            var floosrse = floorService.GetAll();
            var housings = housingService.GetAllActiveHousings();
            var model = new BlockViewModel();

            var blocks = blockService.GetAll();
            foreach (var block in blocks)
            {
                var floors = floorService.GetAllByBlockId(block.Id);
                var floorDtos = new List<FloorDto>();
                foreach (var floor in floors)
                {
                    var floorInBlock = mapper.Map<FloorDto>(floor);
                    floorInBlock.HousingCount = housingService.GetHousingCountByFloorId(floor.Id);
                    floorDtos.Add(floorInBlock);
                }
                var blockModel = new BlockModel
                {
                    block = mapper.Map<BlockDto>(block),
                    floorsInBlokcs = floorDtos
                };
                blockModel.blockHasHirer = blockHasHirerCheck(block.Id);
                model.Blocks.Add(blockModel);
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            //MANUEL OLARAK İSİM VE NUMARA VERİLİYOR

            var blocksCount = blockService.GetAll().Count;
            if (blocksCount == 0)
            {
                blockService.Add(new Block
                {
                    Name = "A",
                    BlockNumber = blocksCount + 1
                });
            }
            else
            {
                var lastBlock = blockService.GetAll().OrderByDescending(b => b.Id).FirstOrDefault();
                blockService.Add(new Block
                {
                    BlockNumber = lastBlock.BlockNumber + 1,
                    Name = getNextChar(Convert.ToChar(lastBlock.Name)).ToString()
                });
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id != null && id > 0)
            {
                var block = blockService.GetById(id);
                var floors = floorService.GetAllByBlockId(id);
                var housings = housingService.GetHousingByBlockId(id);
                foreach (var housing in housings)
                {
                    housingService.Delete(housing);
                }
                foreach (var floor in floors)
                {
                    floorService.Delete(floor);
                }
                blockService.Delete(block);
            }
            return RedirectToAction("Index");
        }
        private bool blockHasHirerCheck(int blockId)
        {
            return housingService.GetHousingByBlockId(blockId).Where(h => h.IsEmpty == false).Any();
        }

        private static char getNextChar(char c)
        {


            int ascii = (int)c;

            int nextAscii = ascii + 1;

            char nextChar = (char)nextAscii;
            return nextChar;
        }
    }


}

Apartment.App/Apartment.App.Web/Controllers/InvoiceTypeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Apartment.App.Business.Abstract;
using Apartment.App.Business.Concrete;
using Apartment.App.Business.DTO;
using Apartment.App.Domain.Entities;
using Apartment.App.Web.Models;
using Apartment.App.Web.Models.InvoiceTypeModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Apartment.App.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InvoiceTypeController : Controller
    {
        private readonly IinvoiceTypeService invoiceTypeService;
        private readonly IMapper mapper;
        public InvoiceTypeController(IinvoiceTypeService invoiceTypeService, IMapper mapper)
        {
            this.invoiceTypeService = invoiceTypeService;
            this.mapper = mapper;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            var types = invoiceTypeService.getAllInvoiceTypes();
            var model = new InvoiceTypeViewModel
            {
                InvoiceTypes = new List<InvoiceTypeDto>()
            };
            foreach (var item in types)
            {
                model.InvoiceTypes.Add(new InvoiceTypeDto()
                {
                    Id=item.Id,
                    Name = item.TypeName,
                    Unit = item.TypeUnit
                });
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Manage( int id )
        {
            var model = new InvoiceTypeManageModel();
            if ( id != 0 )
            {
                var type = invoiceTypeService.GetInvoiceTypeById(id);
                model.Id = type.Id;
                model.Name = type.TypeName;
                model.Unit = type.TypeUnit;
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Manage(InvoiceTypeManageModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0) 
                {
                    invoiceTypeService.Add(model.Name, model.Unit);
                }
                else
                {
                    invoiceTypeService.Update(model.Id, model.Name, model.Unit);
                }
                return  RedirectToAction("Index");
            }
            return View();
        }
    }
}

Apartment.App/Apartment.App.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using Apartment.App.Domain.Entities.IdentityEntities
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Apartman Yönetim Sistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Apartman Yönetim Sistemi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="Partials/_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                            @if (UserManager.IsInRoleAsync(UserManager.FindByNameAsync(SignInManager.Context.User.Identity.Name).Result, "Admin").Result)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="InvoiceType" asp-action="Index">Fatura Tipi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Block" asp-action="Index">Bloklar/Kat Yönet</a>
                                </li>
                            }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Housing" asp-action="Index">Daireler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="Index">Faturalar</a>
                        </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Apartment.App.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>