Apartment.App/Apartment.App.Web/Models/BlockModels/BlockViewModel.cs
using System.Collections.Generic;
using Apartment.App.Business.DTO;

namespace Apartment.App.Web.Models.BlockModels
{
    public class BlockViewModel
    {
        public List<BlockModel> Blocks { get; set; } = new List<BlockModel>();
    }
}

Apartment.App/Apartment.App.Web/Controllers/BlockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using Apartment.App.Business.Abstract;
using Apartment.App.Business.DTO;
using Apartment.App.Domain.Entities;
using Apartment.App.Web.Models.BlockModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace Apartment.App.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlockController : Controller
    {
        private IBlockService blockService;
        private IFloorService floorService;
        private IHousingService housingService;
        private IMapper mapper;
        public BlockController(IBlockService blockService, IFloorService floorService, IHousingService housingService, IMapper mapper)
        {
            this.blockService = blockService;
            this.floorService = floorService;
            this.housingService = housingService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var blocksassd = blockService.GetAll();
            var floosrse = floorService.GetAll();
            var housings = housingService.GetAllActiveHousings();
            var model = new BlockViewModel();

            var blocks = blockService.GetAll();
            foreach (var block in blocks)
            {
                var floors = floorService.GetAllByBlockId(block.Id);
                var floorDtos = new List<FloorDto>();
                foreach (var floor in floors)
                {
                    var floorInBlock = mapper.Map<FloorDto>(floor);
                    floorInBlock.HousingCount = housingService.GetHousingCountByFloorId(floor.Id);
                    floorDtos.Add(floorInBlock);
                }
                var blockModel = new BlockModel
                {
                    block = mapper.Map<BlockDto>(block),
                    floorsInBlokcs = floorDtos
                };
                blockModel.blockHasHirer = blockHasHirerCheck(block.Id);
                model.Blocks.Add(blockModel);
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            //MANUEL OLARAK İSİM VE NUMARA VERİLİYOR

            var blocksCount = blockService.GetAll().Count;
            if (blocksCount == 0)
            {
                blockService.Add(new Block
                {
                    Name = "A",
                    BlockNumber = blocksCount + 1
                });
            }
            else
            {
                var lastBlock = blockService.GetAll().OrderByDescending(b => b.Id).FirstOrDefault();
                blockService.Add(new Block
                {
                    BlockNumber = lastBlock.BlockNumber + 1,
                    Name = getNextChar(Convert.ToChar(lastBlock.Name)).ToString()
                });
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id != null && id > 0)
            {
                var block = blockService.GetById(id);
                var floors = floorService.GetAllByBlockId(id);
                var housings = housingService.GetHousingByBlockId(id);
                foreach (var housing in housings)
                {
                    housingService.Delete(housing);
                }
                foreach (var floor in floors)
                {
                    floorService.Delete(floor);
                }
                blockService.Delete(block);
            }
            return RedirectToAction("Index");
        }
        private bool blockHasHirerCheck(int blockId)
        {
            return housingService.GetHousingByBlockId(blockId).Where(h => h.IsEmpty == false).Any();
        }

        private static char getNextChar(char c)
        {


            int ascii = (int)c;

            int nextAscii = ascii + 1;

            char nextChar = (char)nextAscii;
            return nextChar;
        }
    }


}

Apartment.App/Apartment.App.Web/Controllers/FloorController.cs
using System.Linq;
using Apartment.App.Business.Abstract;
using Apartment.App.Business.DTO;
using Apartment.App.Domain.Entities;
using Apartment.App.Web.Models.FloorModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Apartment.App.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FloorController : Controller
    {
        private IFloorService floorsService;
        private IBlockService blockService;
        private IMapper mapper;
        public FloorController(IFloorService floorservice, IBlockService blokService, IMapper mapper)
        {
            this.floorsService = floorservice;
            this.blockService = blokService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var model = new FloorViewModel();
            var floors = floorsService.GetAll();
            foreach (var floor in floors)
            {
                model.Floors.Add(mapper.Map<FloorDto>(floor));
            }
            return RedirectToAction("Index","Block");
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            var lastFloor = floorsService.GetAllByBlockId(id).OrderByDescending(x => x.Id).FirstOrDefault();
            var newFloor = new FloorDto();
            if (lastFloor == null)
            {
                newFloor.BlockId = id;
                newFloor.FloorNumber = 0;
            }
            else
            {
                newFloor.BlockId = id;
                newFloor.FloorNumber = lastFloor.FloorNumber + 1;
            }
            floorsService.Add(new Floor
            {
                FloorNumber = newFloor.FloorNumber,
                Block = blockService.GetById(newFloor.BlockId),
            });
            return RedirectToAction("Index");
        }

    }
}

Apartment.App/Apartment.App.Web/Views/Block/Index.cshtml
@using Microsoft.CodeAnalysis.FlowAnalysis
@model Apartment.App.Web.Models.BlockModels.BlockViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-between">
    <h2>Blok Yönetim Penceresi</h2>
    <a class="btn btn-success" href="@Url.Action("Add", "Block")">Yeni Blok Ekle</a>
</div>

<div class="container">
    <br>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">

        @for (int i = 0; i < Model.Blocks.Count; i++)
        {
            if (i == 0)
            {
                <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#@("menu"+@Model.Blocks[i].block.BlockNumber.ToString())"> Blok : @Model.Blocks[i].block.BlockNumber</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link " data-toggle="tab" href="#@("menu"+@Model.Blocks[i].block.BlockNumber.ToString())"> Blok : @Model.Blocks[i].block.BlockNumber</a>
                </li>
            }
        }
    </ul>

    <div class="tab-content">

        @for (int i = 0; i < Model.Blocks.Count; i++)
        {
            if (i == 0)
            {
                <div class=" container tab-pane active " id="@("menu"+@Model.Blocks[i].block.BlockNumber.ToString())">
                    @for (int j = 0; j < @Model.Blocks[i].floorsInBlokcs.Count; j++)
                    {
                        <div class="p-3 mb-2 bg-secondary text-white">
                            <br>
                            <p>KAT : @Model.Blocks[i].floorsInBlokcs[j].FloorNumber  MESKEN SAYISI : @Model.Blocks[i].floorsInBlokcs[j].HousingCount</p>
                            <a class="btn btn-success" href="@Url.Action("Add", "Housing",new{floorId=@Model.Blocks[i].floorsInBlokcs[i].Id} )">Yeni Daire Ekle</a>
                        </div>
                    }
                    <br />
                    <a class="btn btn-info" href="@Url.Action("Add", "Floor",new{id=@Model.Blocks[i].block.Id} )">Yeni Kat Ekle</a>
                    @if (@Model.Blocks[i].blockHasHirer == false)
                    {
                        <a class="btn btn-danger" href="@Url.Action("Delete", "Block",new{id=@Model.Blocks[i].block.Id})">Blok Sil</a>
                    }
                </div>
            }
            else
            {
                <div class=" container tab-pane fade" id="@("menu"+@Model.Blocks[i].block.BlockNumber.ToString())">
                    @for (int j = 0; j < @Model.Blocks[i].floorsInBlokcs.Count; j++)
                    {
                        <div class="p-3 mb-2 bg-secondary text-white">
                            <br>
                            <p>KAT : @Model.Blocks[i].floorsInBlokcs[j].FloorNumber  MESKEN SAYISI : @Model.Blocks[i].floorsInBlokcs[j].HousingCount</p>
                            <a class="btn btn-success" href="@Url.Action("Add", "Housing",new{floorId=@Model.Blocks[i].floorsInBlokcs[i].Id} )">Yeni Daire Ekle</a>
                        </div>
                    }
                    <br />
                    <a class="btn btn-info" href="@Url.Action("Add", "Floor",new{id=@Model.Blocks[i].block.Id} )">Yeni Kat Ekle</a>
                    @if (@Model.Blocks[i].blockHasHirer == false)
                    {
                        <a class="btn btn-danger" href="@Url.Action("Delete", "Block",new{id=@Model.Blocks[i].block.Id} )">Blok Sil</a>
                    }
                </div>
            }
        }
    </div>
</div>